import MongooseLib from 'mongoose';

// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

const users = (
   mongoose: MongooseLib.Connection,
   Mongoose: typeof MongooseLib
) => {
   // This section contains the properties of your model, mapped to your collection's properties.
   // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
   const schema = new Mongoose.Schema(
      {
         name: { type: String, required: true },
         surname: { type: String, required: true },
         username: String,
         email: String,
         role: {
            type: String,
            enum: ['admin', 'user'],
            required: true,
         },
         password: String,
      },
      {
         timestamps: false,
      }
   );

   return mongoose.model('users', schema, 'users');
};

export default users;
